Make "Remove an intent" cluster-friendly
MicrosoftDocs/azure-stack-docs pull request #1834
Opened 2022-01-27 23:33 UTC by helmste

Added a script that would remove existing intents, intent-based virtual switches and QoS policies from all nodes of a cluster to allow for successful re-deployment attempt.

2022-01-27 23:33 UTC, PRMerger14 commented
@helmste : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2022-01-28 00:22 UTC, dcuomo requested changes
Hi @helmste - minor wording changes for customer clarity. Otherwise LGTM. Thanks for writing this up!

2022-01-28 00:22 UTC, dcuomo commented on azure-stack/hci/manage/manage-network-atc.md
> +If you previously deployed and configured Network ATC on your system, you may need to reset the cluster or node so that the configuration can be deployed. To do this on a cluster-based deploynent, co
I don't like the terminology of "reset the cluster" which I think gives the wrong impression. Consider: "you may need to remove the existing configuration as Network ATC will not remove them for you." or something to that effect.

" to one cluster node" should be "on one cluster node"

2022-01-28 00:32 UTC, PRMerger12 commented
@helmste : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2022-01-28 00:58 UTC, JasonGerend approved these changes

2022-01-28 00:59 UTC, JasonGerend commented
#sign-off

2022-01-28 02:01 UTC, JasonGerend reviewed
@helmste  Here are my suggested edits from the email thread. I can't edit the heading on line 128 from here, but my suggested heading is: Remove all intents and start over

2022-01-28 02:24 UTC, PRMerger14 commented
@helmste : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2022-01-28 02:24 UTC, PRMerger18 commented
@helmste : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2022-01-28 02:24 UTC, PRMerger18 commented
@helmste : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2022-01-28 17:52 UTC, ktoliver commented
@JasonGerend Could you confirm that you're ready for the PR to be merged? Thanks.

2022-01-28 18:44 UTC, JasonGerend approved these changes

2022-01-28 18:46 UTC, JasonGerend commented
#sign-off. Yes please!

2022-01-28 18:48 UTC, merged