July security update 7B
MicrosoftDocs/azure-stack-docs pull request #3203
Opened 2024-06-28 16:54 UTC by dansisson

2024-06-28 19:03 UTC, Karl-WE requested changes
understand the Core OS is the same but in a docs for Azure Stack HCI, even without a GUI, is it necessary to point out Windows 11 removed features?

2024-06-28 19:05 UTC, Karl-WE reviewed
would propose a deletion.

2024-06-28 19:05 UTC, Karl-WE commented on azure-stack/hci/security-update/hci-security-update-jul-2024.md
> +- **Remote Desktop MultiPoint Server**. A race condition causes the service to stop responding.
these might be obsolete

2024-06-28 21:27 UTC, Court72 commented
@alkohli

Can you review the proposed changes? Note that the new content needs to be moved into the private repo for staging, validation, Acrolinx, and to get it merged.

If you'd like the PR review team's help [moving the commits](https://review.learn.microsoft.com/en-us/help/contribute/contribute-how-to-manage-act-guidelines-public-pr?branch=main#pull-public-commits-to-the-private-repo-for-updates-staging-publication), email the publicprs alias.
	
#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

2024-07-19 19:35 UTC, alkohli commented
@Court72 - could you please close this PR? The content from this PR is captured in another PR and that PR has gone live.  The person who opened this PR has different sets of creds now and is not able to close this PR. Thank you!

2024-07-19 20:22 UTC, closed without merging